services:
  backend: &backend
    build:
      context: .
      dockerfile: ./backend/docker/local/django/Dockerfile
    image: dealsmo_backend
    container_name: dealsmo_backend
    volumes:
      - ./backend:/app:z
      - ./backend/staticfiles:/app/staticfiles
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./backend/.envs/.env.local
    depends_on:
      - postgres
      - mailpit
    command: /start
    networks:
      - dealsmo_nw

  postgres:
    build:
      context: .
      dockerfile: ./backend/docker/local/postgres/Dockerfile
    image: dealsmo_postgres
    container_name: dealsmo_postgres
    ports:
      - "5432:5432"
    volumes:
      - dealsmo_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.envs/.env.local
    networks:
      - dealsmo_nw

  mailpit:
    image: docker.io/axllent/mailpit:v1.15
    container_name: dealsmo_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:  
      - dealsmo_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1  
    networks:
      - dealsmo_nw

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/local/Dockerfile
    container_name: dealsmo_frontend
    image: dealsmo_frontend
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./frontend:/app
      - frontend_data:/app/node_modules
    networks:
      - dealsmo_nw

  nginx:
    build:
      context: ./backend/docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: dealsmo_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - backend
    networks:
      - dealsmo_nw 

networks:
  dealsmo_nw:
    external: true

volumes:
  dealsmo_postgres_data: {}
  dealsmo_mailpit_data: {}
  logs_store: {}
  frontend_data: {}
