# Generated by Django 5.0.2 on 2025-01-26 18:41

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_occupation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country_of_origin",
            field=django_countries.fields.CountryField(
                default="USA", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("content_manager", "Content Manager"),
                    ("digital_marketing", "Digital Marketing"),
                    ("customer_support", "Customer Support"),
                    ("data_analyst", "Data Analyst"),
                    ("graphic_designer", "Graphic Designer"),
                    ("legal_compliance", "Legal Compliance"),
                    ("tenant", "Tenant"),
                ],
                default="tenant",
                max_length=20,
                verbose_name="Occupation",
            ),
        ),
    ]
